/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Download: typeof import('./src/components/Icons/Download.vue')['default']
    Dropper: typeof import('./src/components/Icons/Dropper.vue')['default']
    DropperMinimalistic2SvgrepoCom: typeof import('./src/components/Icons/DropperMinimalistic2SvgrepoCom.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    Redo: typeof import('./src/components/Icons/Redo.vue')['default']
    Remove: typeof import('./src/components/Icons/Remove.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Icons/Settings.vue')['default']
    Sort: typeof import('./src/components/Icons/Sort.vue')['default']
    SvgList: typeof import('./src/components/SvgList/index.vue')['default']
    TargetSvgrepoCom: typeof import('./src/components/Icons/TargetSvgrepoCom.vue')['default']
    Undo: typeof import('./src/components/Icons/Undo.vue')['default']
    Upload: typeof import('./src/components/Icons/Upload.vue')['default']
  }
}
